# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_csv_to_db.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # set main window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 479)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # title dbsm
        self.title_dbsm = QtWidgets.QLabel(self.centralwidget)
        self.title_dbsm.setGeometry(QtCore.QRect(10, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Amiri")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_dbsm.setFont(font)
        self.title_dbsm.setObjectName("title_dbsm")

        # title framework
        self.title_framework = QtWidgets.QLabel(self.centralwidget)
        self.title_framework.setGeometry(QtCore.QRect(10, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Amiri")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_framework.setFont(font)
        self.title_framework.setObjectName("title_framework")

        # mysql
        self.btn_mysql = QtWidgets.QRadioButton(self.centralwidget)
        self.btn_mysql.setGeometry(QtCore.QRect(10, 90, 82, 17))
        self.btn_mysql.setObjectName("btn_mysql")

        # laravel
        self.btn_laravel = QtWidgets.QRadioButton(self.centralwidget)
        self.btn_laravel.setGeometry(QtCore.QRect(10, 250, 82, 17))
        self.btn_laravel.setObjectName("btn_laravel")

        # send btn
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(0, 400, 631, 71))
        self.send.setObjectName("send")

        # select csv btn
        self.btn_select_csv = QtWidgets.QPushButton(self.centralwidget)
        self.btn_select_csv.setGeometry(QtCore.QRect(290, 60, 75, 23))
        self.btn_select_csv.setObjectName("btn_select_csv")

        # display csv filepath
        self.csv_filepath_display = QtWidgets.QLineEdit(self.centralwidget)
        self.csv_filepath_display.setEnabled(True)
        self.csv_filepath_display.setGeometry(QtCore.QRect(370, 60, 231, 20))
        self.csv_filepath_display.setText("")
        self.csv_filepath_display.setReadOnly(False)
        self.csv_filepath_display.setObjectName("csv_filepath_display")

        # btn migration file for framework
        self.btn_migration_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_migration_file.setGeometry(QtCore.QRect(290, 110, 111, 23))
        self.btn_migration_file.setObjectName("btn_migration_file")

        # btn seeder file for framework
        self.btn_seeder_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_seeder_file.setGeometry(QtCore.QRect(290, 150, 111, 23))
        self.btn_seeder_file.setObjectName("btn_seeder_file")

        # select migration seeder for dbsm
        self.select_migration_seeder = QtWidgets.QComboBox(self.centralwidget)
        self.select_migration_seeder.setGeometry(QtCore.QRect(290, 190, 231, 22))
        self.select_migration_seeder.setObjectName("btn_dbsm_migration_seeder")
        self.select_migration_seeder.addItem("")
        self.select_migration_seeder.addItem("")
        self.select_migration_seeder.addItem("")

        # display migration filepath for framework
        self.label_migration_file = QtWidgets.QLabel(self.centralwidget)
        self.label_migration_file.setGeometry(QtCore.QRect(410, 110, 221, 16))
        self.label_migration_file.setObjectName("label_migration_file")

        # display seeder filepath for framework
        self.label_seeder_file = QtWidgets.QLabel(self.centralwidget)
        self.label_seeder_file.setGeometry(QtCore.QRect(410, 150, 221, 16))
        self.label_seeder_file.setObjectName("label_seeder_file")

        # save in for dbsm
        self.btn_save_dbsm = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save_dbsm.setGeometry(QtCore.QRect(290, 230, 111, 23))
        self.btn_save_dbsm.setObjectName("btn_save_dbsm")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_dbsm.setText(_translate("MainWindow", "DBSM"))
        self.title_framework.setText(_translate("MainWindow", "Framework"))
        self.btn_mysql.setText(_translate("MainWindow", "Mysql"))
        self.btn_laravel.setText(_translate("MainWindow", "Laravel"))
        self.send.setText(_translate("MainWindow", "Generate"))
        self.btn_select_csv.setText(_translate("MainWindow", "Select CSV"))
        self.btn_migration_file.setText(_translate("MainWindow", "migration file"))
        self.btn_seeder_file.setText(_translate("MainWindow", "seeder file"))
        self.select_migration_seeder.setItemText(0, _translate("MainWindow", "migration"))
        self.select_migration_seeder.setItemText(1, _translate("MainWindow", "seeder"))
        self.select_migration_seeder.setItemText(2, _translate("MainWindow", "migration + seeder"))
        self.label_migration_file.setText(_translate("MainWindow", "TextLabel"))
        self.label_seeder_file.setText(_translate("MainWindow", "TextLabel"))
        self.btn_save_dbsm.setText(_translate("MainWindow", "save in"))

    # -------------------------------
    # method for btn
    # -------------------------------



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
